version: "3"
services:
  riva-wordpress:
    container_name: riva-wp
    depends_on:
    - riva-mysql
    image: riva-wordpress:latest 
    ports:
    - "8000:80"
    env_file:
      ./init/local.env
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./init/wp-config.php:/var/www/html/wp-config.php
    networks:
      - riva-site-net
  riva-mysql:
    container_name: riva_mysql
    image: mysql:8.0
    restart: always
    env_file:
      ./init/local.env
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - riva-site-net
  phpmyadmin:
    depends_on:
      - riva-mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql_db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      UPLOAD_LIMIT: 900M
    networks:
      - riva-site-net
networks:
  riva-site-net:
